<?php
return [
	'password',
	'name'=>'password',
	'text'=>'密码',
	'attrs'=>[
		'class'=>'form-control',
		'required'=>1,
		'placeholder'=>'请输入密码',
		'autocomplete'=>'new-password',
	],
	'event'=>[
		'beforeAdd'=>function($element){
			
			$controller=\xqkeji\App::getController();
			$actionName=$controller->getActionName();
			if($actionName=='edit')
			{
				$attributes=$element->getAttrs();
				unset($attributes['required']);
				$attributes['placeholder']='请输入密码(不用修改密码时，不要填写)';
				$element->setAttrs($attributes);
				$element->setValidators([]);
			}
		},
	],
	'filters'=>['string'],
	'validators'=>[
		[
			'required',
		]
	],
];