<?php
return [
	'list_form',
	'row'=>[
		'class'=>'text-center',
	],
	[
		'ListId',
		'ListReserveStudentNo',
		'ListReserveStudentName',
		'ListReserveBuilding',
		'ListReserveRoom',
		'ListReserveSeat',
		'ListReserveTime',
		'ListReserveDate',
		'ListCreateTime',
		'ListDelete',
	]
];
